name: coingecko-dashboard
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - fastapi==0.104.1
    - httpx==0.25.2
    - cachetools==5.3.2
    - uvicorn[standard]==0.24.0
    - python-multipart==0.0.6
    - python-dotenv==1.0.0
    - pydantic==2.5.0
    - typing-extensions==4.8.0
    # Development dependencies
    - pytest==7.4.3
    - pytest-asyncio==0.21.1
    - black==23.11.0
    - flake8==6.1.0
    - mypy==1.7.1
